name: 'Docker Publish Schedule'

on:
  schedule:
    - cron: '0 0 10,20,30 * *'

jobs:
  publish:
    name: Docker Publish Schedule
    runs-on: ubuntu-latest
    steps:
      -
        name: Get Tag
        id: tag
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        with:
          repository: ${{ github.repository }}
          excludes: prerelease, draft
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: refs/tags/${{ steps.tag.outputs.release }}
      -
        name: Prepare
        id: pre
        run: |
          TAG=${{ steps.tag.outputs.release }}
          echo ::set-output name=tag::${TAG#v}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: '.'
          file: './Dockerfile'
          platforms: 'linux/amd64,linux/arm64,linux/arm/v7'
          push: true
          tags: |
            ttionya/vaultwarden-backup:latest
            ttionya/vaultwarden-backup:${{ steps.pre.outputs.tag }}
            ttionya/bitwardenrs-backup:latest
            ttionya/bitwardenrs-backup:${{ steps.pre.outputs.tag }}
