name: 'Docker Publish Description'

on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/docker-description.yml

jobs:
  sync:
    name: Docker README.md Sync

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: DockerHub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: 'ttionya/vaultwarden-backup'
          enable-url-completion: true
      -
        name: DockerHub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: 'ttionya/bitwardenrs-backup'
          enable-url-completion: true
